<?php

/**
 * @file
 * Setup infrastructure news feed.
 */

use Drupal\feeds\Entity\Feed;

/**
 * Implements hook_install().
 */
function infrastructure_news_config_install() {
  $feed = Feed::create([
    'type' => "infrastructure_news_feed",
    'title' => "Infrastructure News",
    'source' => "https://operations-api.access-ci.org/wh2/news/v1/affiliation/access-ci.org/all_outages/",
    'uid' => 1,
  ]);
  $feed->save();
}
